apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: ml-fastapi
          imagePullPolicy: Never
          ports:
            - containerPort: 8000